apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: allow
  namespace: argocd
spec:
  description: "Project for allowing everything"
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'