apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/albertopeisan/argocd
    path: argocd
    directory:
      recurse: true
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
