# This manifest written by Jolene Engo <dev.toaster@gmail.com>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: allow
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: v8.6.5
    helm:
      parameters:
        - name: certmanager-issuer.email
          value: me@example.com
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true