apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: allow
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.24.2
    chart: base
    helm:
      parameters:
        - name: defaultRevision
          value: default
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
